Feature/client-service
RubenDelReyBabel/Sesion9 pull request #3
Opened 2024-03-14 11:21 UTC by Antonio-LAndrade-Babel

Se crea el servicio para el Client. Se compone de:

Clases del paquete «service»:
- ClientService
- ClientServiceImpl

Clases del paquete «repository»:
- ClientRepository

2024-03-14 12:25 UTC, RubenDelReyBabel requested changes

2024-03-14 12:25 UTC, RubenDelReyBabel commented on src/main/java/com/babelgroup/service/ClientService.java
> +    Client updateClient(String clientId, Client clientDetails);
No es necesario pasar el id del cliente, este ya está en el objeto

2024-03-14 12:25 UTC, RubenDelReyBabel commented on src/main/java/com/babelgroup/service/ProductService.java
> +    Product updateProduct(String id, Product productDetails);
No es necesario el id del producto, ya está en el objeto producto

2024-03-15 09:49 UTC, VictorValero9 approved these changes

2024-03-15 09:50 UTC, merged